# Generated by Django 6.0 on 2026-04-07 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits_app', '0001_initial'),
        ('stock_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mouvementstock',
            options={'ordering': ['-date_mouvement'], 'verbose_name': 'Mouvement de stock'},
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='date_mouvement',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='motif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='produits_app.produit'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('AJUSTEMENT', 'Ajustement'), ('PERTE', 'Perte'), ('RETOUR', 'Retour client')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
